# <center> Harlinton Palacios Mosquera</center>
# <center>161041033</center>

#  <CENTER>PART 1. Classifier Based on KNN using Euclidean distance.</CENTTER>

In [1]:
import math
import numpy as np
import operator
import random
import time
from sklearn import svm
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools

In this section I import all the different libraries that I will use in the development of this work

In [2]:
def euclideandis_distance(x,y):
    dis=0
    for i in range(0, len(x)):
        dis += math.pow((x[i] - y[i]), 2)
    return math.sqrt(dis)

# manhattan distance
def manhattandis_distance (x,y):
    dis=0
    for i in range(0, len(x)):
        dis += abs(x[i] - y[i])
    return dis

In [3]:
def read_data(file_path):
    data_set = []
    with open(file_path) as f:
        for row in f:
            row = row.replace("\n", "")
            row = row.replace("\t", " ")
            tab = row.split(" ")
            tab = filter(None, tab)
            data_set.append(map(float, tab))
        np.random.shuffle(data_set)
    return np.array(data_set)


I define the two equations I am going to use:

<b>The Euclidean distance or Euclidean metric</b> is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm. Older literature refers to the metric as Pythagorean metric.

<img src="http://mines.humanoriented.com/classes/2010/fall/csci568/portfolio_exports/sphilip/images/euclid_eqn.gif" alt="Drawing" style="width: 400px;"/>


<b>Manhattan distance (plural Manhattan distances)</b> The distance between two points in a grid based on a strictly horizontal and/or vertical path (that is, along the grid lines), as opposed to the diagonal or "as the crow flies" distance.

<img src="http://angiogenesis.dkfz.de/oncoexpress/software/cs_clust/dist_004.gif" alt="Drawing" style="width: 300px;"/>


In [4]:
def k_nearest_neighbors(Xtrain, Xtest, Ytrain, k, distanceMetric):
    Ypred = []
    for vect in Xtest:
        distances = []
        for x, y in zip(Xtrain, Ytrain):
            distances.append((y, distanceMetric(x, vect)))
        distances.sort(key=operator.itemgetter(1))
        distances = distances[:k]
        dictionary = {}
        for tuple in distances:
            #if not dictionary.has_key(tuple[0]):
            if not (tuple[0]) in  dictionary:  
                dictionary[tuple[0]] = 1
            else:
                dictionary[tuple[0]] += 1
        Ypred.append(max(dictionary, key=dictionary.get))
    return Ypred


In [5]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
 
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In this section, I generate the function of the nearest neighbor, adding the necessary parameters for its execution, such as training data, test data of the equation and the value of k.

<b>K nearest neighbors </b> is a simple algorithm that stores all available cases and classifies new cases based on a similarity measure (e.g., distance functions). KNN has been used in statistical estimation and pattern recognition already in the beginning of 1970's as a non-parametric technique



In [ ]:
def confusion(Ytest, Ypred, nb):
    confmat = np.zeros((nb, nb))
    for y, y_ in zip(Ytest, Ypred):
        confmat[y-1][y_-1] += 1
    return confmat


def calculate_recall(confmat):
    recall = 0
    i = 0
    for x in np.diagonal(confmat):
        s = sum(np.transpose(confmat)[i])
        if s == 0:
            i += 1
            continue
        recall += x / s
        i+=1
    return recall / i

def calculate_precision(confmat):
    precision = 0
    i = 0
    for x in np.diagonal(confmat):
        s = sum(confmat[i])
        if s == 0:
            i += 1
            continue
        precision += x / s
        i+=1
    return precision / i

def calculate_acc(confmat):
    return sum(confmat.diagonal()) / sum(sum(confmat))


In this section I generate all the functions that will help me with giving results, such as:

• Recall function it takes the confusion matrix for calculating the recall measure. 

• Precision function: it takes the confusion matrix for calculating the precision measure.

• Accuracy function: it takes the confusion matrix for calculating the accuracy measure.


In [7]:
iris = load_iris()
data_leaf='leaf.dat'
data = read_data(data_leaf)
splits = 4
X = iris.data
y = iris.target
class_names = iris.target_names
k = 5
accuracy = 0
recall = 0
precision = 0
ella= 4
kfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
for train_index, test_index in kfold.split(X, y):
    Xtrain = X[train_index]
    Xtest = X[test_index]
    Ytrain = y[train_index]
    Ytest = y[test_index]
    
    
    start_time = time.time()
    Ypred = k_nearest_neighbors(Xtrain, Xtest, Ytrain, k, manhattandis_distance)
    
    confmat = confusion(Ytest, Ypred, max(Ytrain))
    accuracy += calculate_acc(confmat)
    recall += calculate_recall(confmat)
    precision += calculate_precision(confmat)

print ("ACCURACY : ", (accuracy) / (ella))
print ("PRECISION : ", precision / (ella))
print ("RECALL : ", recall /(ella))
print("Time: %s secs" % (time.time() - start_time))


ACCURACY :  0.952991452991
PRECISION :  0.949118589744
RECALL :  0.949164377289
Time: 0.02001190185546875 secs


# leaf.dat
ACCURACY  = 0.129411764706

PRECISION = 0.113078703704

RECALL = 0.11539376904

Time 0.259999990463 secs

In [8]:
def confusionMatrices():
    cnf_matrix = confusion_matrix(Ytest, Ypred)
    np.set_printoptions(precision=2)

    # Plot non-normalized confusion matrix
    plt.figure()
    plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix, without normalization')

    # Plot normalized confusion matrix
    plt.figure()
    plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

    
confusionMatrices()

Confusion matrix, without normalization
[[12  0  0]
 [ 0 11  1]
 [ 0  1 11]]
Normalized confusion matrix
[[ 1.    0.    0.  ]
 [ 0.    0.92  0.08]
 [ 0.    0.08  0.92]]


This is one of the most important funsion because it generates the results of ACC, PRECISION, RECALL AND EXECUTION TIME also this section I declare some vital variables for the execution of algorithm such as:
(K) related to Nearest Neighbor
(iris) saves the data from the iris database
(splits) Number of folds
X, and I assign the data and the targets of the iris data
Accuracy, recall and precision which keep the data corresponding to each variable.


Also in this session I download the iris data base from the sklearn.datasets library, which is a simpler way to get some databases without downloading  files and then read it also in this section is the division of data, for this I used k-fold cross validation.

In KFolds, each test set should not overlap, even with shuffle. With KFolds and shuffle, the data is shuffled once at the start, and then divided into the number of desired splits. The test data is always one of the splits, the train data is the rest. In ShuffleSplit, the data is shuffled every time, and then split.


# <center>Part 2: classifier based on KNN using Manhattan distance.</center>

In [9]:
accuracy = 0
recall = 0
precision = 0

kfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)

for train_index, test_index in kfold.split(X, y):
    Xtrain = X[train_index]
    Xtest = X[test_index]
    Ytrain = y[train_index]
    Ytest = y[test_index]
    
    
    start_time = time.time()
    
    
    Ypred = k_nearest_neighbors(Xtrain, Xtest, Ytrain, k, euclideandis_distance)
    
    
    confmat = confusion(Ytest, Ypred, max(Ytrain))
    accuracy += calculate_acc(confmat)
    recall += calculate_recall(confmat)
    precision += calculate_precision(confmat)

print ("ACCURACY : ", (accuracy) / (ella))
print ("PRECISION : ", precision / (ella))
print ("RECALL : ", recall /(ella))
print("Time: %s secs" % (time.time() - start_time))


ACCURACY :  0.952457264957
PRECISION :  0.943509615385
RECALL :  0.951163836164
Time: 0.024018526077270508 secs


# leaf.dat
ACCURACY:  0.254901960784

PRECISION:  0.252698412698

RECALL:     0.354533497903

Time:  0300002098083


In [10]:
def confusionMatrices():
    cnf_matrix = confusion_matrix(Ytest, Ypred)
    np.set_printoptions(precision=2)

    # Plot non-normalized confusion matrix
    plt.figure()
    plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix, without normalization')

    # Plot normalized confusion matrix
    plt.figure()
    plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

    
confusionMatrices()

Confusion matrix, without normalization
[[12  0  0]
 [ 0 10  2]
 [ 0  1 11]]
Normalized confusion matrix
[[ 1.    0.    0.  ]
 [ 0.    0.83  0.17]
 [ 0.    0.08  0.92]]


In relation to paragraphs 1 and 2 in which we used two different distance metrics (Euclidean distance and Manhattan distance) in conjunction with Iris data set, we can observe that for this set of data we obtained very similar results using Euclidean distance all the values of Accuracy and accuracy are very similar to the Manhattan distance.

In [12]:
from sklearn.metrics import classification_report
report = classification_report(Ytest, Ypred)
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.91      0.83      0.87        12
          2       0.85      0.92      0.88        12

avg / total       0.92      0.92      0.92        36

